language: python
virtualenv:
  # For scipy
  system_site_packages: false
python:
  # We rely on the Ubuntu python-scipy package, and that's only
  # available for python 2.7 (and 3.something, but pyrerp doesn't
  # support py3 yet)
  - 2.7
before_install:
  - echo Preinstalled
  - pip freeze
  - sudo apt-get install -qq python-scipy python-pandas cython
  - echo Available by apt-get
  - pip freeze
  # Need something like scipy 0.10, pandas 0.12, not sure about cython (want memoryview support anyway, 0.15 does NOT work, 0.19 does)
  - pip install --use-mirrors --upgrade coverage cython patsy pandas
  - echo Final installation
  - pip freeze
  - which nosetests
  - python -c 'import numpy; print(numpy.__version__)'
install:
  - python setup.py install
script:
  - python test-script.py
  - nosetests --exe --failure-detail --all-modules pyrerp/incremental_ls.py:test_foo || true
  # We change directories to make sure that python won't find the copy
  # of the package inside the source directory.
  - export PYRERP_TEST_DATA=$PWD/test-data
  - mkdir empty
  - cd empty
  - INSTALLDIR=$(python -c "import os; import pyrerp; print(os.path.dirname(pyrerp.__file__))")
  - export PYTHONWARNINGS=default PYRERP_FORCE_NO_WARNINGS=1
  - echo $INSTALLDIR
  # The --exe is because python sometimes marks all installed modules
  # as executable, so without --exe nosetests will just ignore
  # everything. Baffling, but so it goes.
  #- coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR
  #- $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR
  #- nosetests --exe --failure-detail --all-modules $INSTALLDIR
  #- coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR/incremental_ls.py
  #- nosetests --exe --failure-detail --all-modules $INSTALLDIR/incremental_ls.py
  #- coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR/incremental_ls.py:test_foo
  - nosetests --exe --failure-detail --all-modules $INSTALLDIR/incremental_ls.py:test_foo
  #- coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR/incremental_ls.py:test_incremental_ls
  #- nosetests --exe --failure-detail --all-modules $INSTALLDIR/incremental_ls.py:test_incremental_ls
notifications:
  email:
    - njs@pobox.com
after_success:
  - pip install --use-mirrors coveralls && coveralls
