language: python
python:
  - 2.7
before_install:
  - sudo apt-get -qq build-dep python-scipy
  - pip install --use-mirrors --upgrade scipy
install:
  - true
script:
  - python test-script.py || true
  - python test-script2.py || true
  - python -c 'import pyrerp.test_foo; pyrerp.test_foo.test_foo()' || true
  - python -c 'import pyrerp.test_bar' || true
  - python -c 'import pyrerp' || true
  - python -c 'import testmod' || true
notifications:
  email:
    - njs@pobox.com
